### ISSUE TITLE
Support CURIEs as RDF/JSON predicates?

### ISSUE THREAD

**Issue by artob** [ruby-rdf/rdf-json#1]
As a straightforward extension of strict [RDF/JSON](http://n2.talis.com/wiki/RDF_JSON_Specification), consider implementing support for parsing [CURIE](http://www.w3.org/TR/curie/) predicates (e.g. "[foaf:name]" instead of "http://xmlns.com/foaf/0.1/name") in the `RDF::JSON::Reader` class.

**Comment by gkellogg** [comment]
Closing this long dormant issue. Adding CURIE/PName support to RDF/JSON would be an incompatible extension, and is solved by using JSON-LD.
