### ISSUE TITLE
RDF::Reader.for(:json) returns nil

### ISSUE THREAD

**Issue by dkinzer** [ruby-rdf/rdf-json#7]
According to the docs `RDF::Reader.for(:json)` should return `RDF::JSON::Reader` but  is returning nil instead.

**Comment by gkellogg** [comment]
The defined extension for RDF/JSON is ".rj", as defined in the [RDF/JSON NOTE](https://www.w3.org/TR/2013/NOTE-rdf-json-20131107/#sec-mediaReg). Why would you expect this format to respond to ".json"?

**Comment by gkellogg** [comment]
Okay, never mind, this is an error in the Reader documentation, it should be ".rj". I'll fix that and turn the test into a negative test.
